INSERT INTO tb_genre (name) VALUES ('ficção cientifica');
INSERT INTO tb_genre (name) VALUES ('Comedia romantica');
INSERT INTO tb_genre (name) VALUES ('Acão');
INSERT INTO tb_genre (name) VALUES ('Drama');
INSERT INTO tb_genre (name) VALUES ('Terror');

INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Matrix', 'Reloaded, a grande batalha para proteger o escolhido, aquele que pode nos salvar das sentinelas.', 1999, 'https://i.ytimg.com/vi/rQO0qJXk50M/maxresdefault.jpg', 'Após enfrentar os sentinelas no mundo real, Neo, a maior esperança da humanidade, está preso entre a Matrix e a realidade. A maioria da população do planeta permanece em um estado de suspensão da realidade virtual. Os poucos humanos que estão cientes das duras realidades tentam desesperadamente afastar as máquinas a tempo de Neo escapar e salvar o dia. Mas as coisas pioram quando o poderoso programa de computador, Agente Smith, aparece na forma humana.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('A Proposta', 'A química entre Reynolds e Bullock, a historia de amor entre Reynolds e sua chefe.', 2009, 'https://img1.hotstarext.com/image/upload/f_auto,t_hcdl/sources/r1/cms/prod/6737/906737-h', 'Margaret Tate é uma poderosa editora de livros que corre o risco de ser deportada para o Canadá, seu país natal. Para poder permanecer em Nova York, ela diz estar noiva de Andrew, seu assistente. O jovem aceita ajudá-la, mas impõe algumas condições, entre elas ir para o Alasca e conhecer sua família excêntrica. Com um oficial da imigração sempre à espreita, Margaret e Andrew têm que seguir o plano de casamento apesar de diversos problemas.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Transformers', 'O Último Cavaleiro, a batalhas contra marquinhas alienígenas para salvar o mundo.', 2017, 'https://i0.wp.com/br.nacaodamusica.com/wp-content/uploads/2017/08/Transformers-5-The-Last-Knight-Online-Trailer.jpg', 'O gigante Optimus Prime embarca em uma das missões mais difíceis de sua vida: encontrar, no espaço sideral, os Quintessons, seres que possivelmente são os responsáveis pela criação da raça Transformers. O problema é que, enquanto isso, seus amigos estão precisando de muita ajuda na Terra, já que uma nova ameaça alienígena resolveu destruir toda a humanidade.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Maze Runner', 'Correr ou Morrer, a corrida no labirinto para a sobrevivência ', 2014, 'https://1.bp.blogspot.com/-2l9pR9jcS1A/WlAL2rzAuQI/AAAAAAAACaE/tj1yh_8tmxUM_irMrdb0rCvi51GRLxyzACLcBGAs/s1600/the_maze_runner-wide.jpg', 'Em um futuro, meio apocalíptico, meio utópico, o jovem Thomas é escolhido para enfrentar o sistema. Ao acordar dentro de um escuro elevador em movimento, ele não consegue se lembrar nem de seu nome. Na comunidade isolada em que foi abandonado, ele conhece outros garotos que passaram pelo mesmo. Para conseguir escapar, Thomas precisa descobrir os sombrios segredos guardados em sua mente e correr muito.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Forrest Gump', 'O Contador de Histórias, uma vida de sonhos contado por um sonhador', 1994, 'http://1.bp.blogspot.com/-V4bMw_BZxXU/T4I-fmTgjWI/AAAAAAAABI8/z6YieOX4tn4/s640/Forrest+Gump.jpg', 'Quarenta anos da história dos Estados Unidos, vistos pelos olhos de Forrest Gump (Tom Hanks), um rapaz com QI abaixo da média e boas intenções. Por obra do acaso, ele consegue participar de momentos cruciais, como a Guerra do Vietnã e Watergate, mas continua pensando no seu amor de infância, Jenny Curran.', 4);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Espiral', 'O Legado de Jogos Mortais, a sobrevivência depende da união.', 2021, 'https://www.arrobanerd.com.br/wp-content/uploads/2021/04/espiral-novo-dest.jpg', 'Sob o comando do veterano da polícia Marcus (Samuel L. Jackson), o detetive Ezekiel Zeke Banks (Chris Rock) se une ao seu parceiro novato Willem (Max Minghella) para desvendar uma série de assassinatos terríveis que estão acontecendo na cidade. Durante as investigações, Zeke acaba se envolvendo no mórbido jogo do assassino. Classificação indicativa 18 anos, contém drogas, violência extrema e linguagem imprópria.', 5);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Velozes & Furiosos 5', 'Operação Rio,  estamos a penas a uma corrida para a vitória.', 2011, 'https://i.ytimg.com/vi/b-uc_79e6L0/maxresdefault.jpg', 'Dominic Toretto descobre que sua amada Letty foi assassinada e resolve procurar pelo autor do crime. Enquanto isso, o agente Brian OConner está em busca de um traficante de drogas. Eles percebem que talvez procurem a mesma pessoa.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Velozes & Furiosos 3', 'Desafio em Tóquio, a velocidade vai além da honram, corra para sobreviver.', 2006, 'https://i.ytimg.com/vi/OhhmaNamPSc/hqdefault.jpg', 'Sean Boswell é um piloto de rua que desafia seu rival e bate o carro no fim da corrida. Então, Sean decide se mudar para o Japão em companhia de seu pai para evitar a prisão nos Estados Unidos, já que os rachas não são nada populares com as autoridades. Em Tóquio, ele começa a aprender um excitante e perigoso estilo novo de competir nas ruas. Só que os riscos ficam ainda mais altos quando Sean decide competir com o campeão local e acaba se apaixonando pela namorada dele.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('John wick 2', 'Um novo dia para matar, uma nova prestação de contas com a vida', 2017, 'https://i1.wp.com/espalhafactos.com/wp-content/uploads/2016/12/john-wick-chapter-2-nycc-poster.jpg?fit=1200%2C675&ssl=1', 'Após recuperar seu carro, John Wick (Keanu Reeves) acredita que enfim poderá se aposentar. Entretanto, a reaparição de Santino D Antonio (Riccardo Scarmacio) atrapalha seus planos. Dono de uma promissória em nome de Wick, por ele usada para deixar o posto de assassino profissional da Alta Cúpula, Santino cobra a dívida existente e insiste para que ele mate sua própria irmã, Gianna (Claudia Gerini).', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Como se Fosse a Primeira Vez', 'A arte da conquista diária, todo dia e um dia ideal para se apaixonar', 2004, 'https://trabalhosparaescola.com.br/wp-content/uploads/2019/07/Como-se-fosse-a-primeira-vez.jpg', 'Henry Roth é um veterinário paquerador, que vive no Havaí, e famoso pelo grande número de turistas que conquista. Seu novo alvo é Lucy Whitmore, que mora no local e por quem Henry se apaixona perdidamente. Mas Lucy sofre de falta de memória de curto prazo e, por isso, ela rapidamente se esquece de fatos que acabaram de acontecer. Assim, Henry é obrigado a conquistá-la, dia após dia, para ficar ao seu lado.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Círculo de Fogo', 'A Revolta” fracassa por não entender universo criado por Guillermo del Toro.', 2013, 'https://estalagemnerd.com.br/wp-content/uploads/2018/03/Circulo-de-Fogo-2-49-Estalagem-Nerd-CAPA.jpg', 'Criaturas monstruosas conhecidas como Kaiju começam a emergir do mar. Para combatê-los, a humanidade desenvolve uma série de robôs gigantescos, os Jaegers. Cada um é controlado por duas pessoas por meio de uma conexão neural. Entretanto, mesmo os Jaegers se mostram insuficientes para derrotar os Kaiju. Diante deste cenário, a última esperança é um velho robô, que passa a ser comandado por um antigo piloto e uma pessoa em treinamento.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('No Limite do Amanhã', 'Mas uma oportunidade de salva a humanidade da invasão alienígena', 2014, 'https://is5-ssl.mzstatic.com/image/thumb/XKlagwvmAgZPDgWi6h3lCg/1200x675.jpg', 'Quando a Terra é tomada por alienígenas, Bill Cage é obrigado a juntar-se às Forças Armadas e ir para a linha de frente no dia do confronto final. Inexplicavelmente ele acaba preso no tempo, condenado a reviver esta data repetidamente. A cada morte e renascimento, Cage adquire mais conhecimento e, antecipando os acontecimentos, tem a chance de mudar o curso da batalha com o apoio', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Vingadores', 'Ultimato, recuperando as forças para a batalha épica contra Thanos ', 2019, 'https://www.blogsoestado.com/marciohenrique/files/2019/09/VINGADORES-ULTIMATO-2019.jpg', 'Em Vingadores: Ultimato, após Thanos eliminar metade das criaturas vivas em Vingadores: Guerra Infinita, os heróis precisam lidar com a dor da perda de amigos e seus entes queridos. Com Tony Stark (Robert Downey Jr.) vagando perdido no espaço sem água nem comida, o Capitão América/Steve Rogers (Chris Evans) e a Viúva Negra/Natasha Romanov (Scarlett Johansson) precisam liderar a resistência contra o titã louco.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Ilha do Medo', 'A investigação de Edward Daniels em uma prisão psiquiátrica escondida numa ilha remota', 2010, 'https://www.nivelepico.com/wp-content/uploads/2010/12/ilha-do-medo-1.jpg', '1954. Teddy Daniels (Leonardo DiCaprio) investiga o desaparecimento de um paciente no Shutter Island Ashecliffe Hospital, em Boston. No local, ele descobre que os médicos realizam experiências radicais com os pacientes, envolvendo métodos ilegais e anti-éticos. Teddy tenta buscar mais informações, mas enfrenta a resistência dos médicos em lhe fornecer os arquivos que possam permitir que o caso seja aberto. Quando um furacão deixa a ilha sem comunicação, diversos prisioneiros conseguem escapar e tornam a situação ainda mais perigosa.', 4);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Sangue no Gelo', 'A investigação de Jack Halcombe em busca de um fantasma conhecido como serial killer.', 2013, 'https://br.web.img2.acsta.net/pictures/210/179/21017992_20130705200354246.jpg', 'O detetive Jack Halcombe está investigando os crimes de Robert Hansen, um assassino em série que, há 13 anos, tem espalhado terror pelas ruas da cidade de Anchorage, no Alasca. Ele já sequestrou mais de 20 mulheres e as deixou na mata, só pelo prazer doentio de caçá-las. Cindy Paulson, uma jovem de 17 anos, consegue escapar das garras de Hansen e resolve ajudar o detetive Halcombe a prender o assassino.', 5);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('O Amor Não Tira Férias', 'A surpresa vem em poucas palavras, simplesmente acontece.', 2014, 'https://occ-0-1068-92.1.nflxso.net/dnm/api/v6/X194eJsgWBDE2aQbaNdmCXGUP-Y/AAAABQm-Xa4zyRIozAKMYlACXTkfKxAt1fz3PDUHe46PlxXpIhitB11CCCNPP8_3ld0shf-iHhcWDkn-5_SGqdsPxPT1c9cU.jpg?r=2d1', 'Tom é um jovem que evita compromissos sérios e tem várias namoradas. Hannah, sua melhor amiga, encontra o homem ideal justamente quando Tom descobre que realmente a ama. No entanto, Hannah pede para ele participar de sua festa de despedida, e Tom aproveita essaa oportunidade para tentar evitar que o casamento aconteça.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Círculo de Fogo 2', 'O Retorno” fracassa por não entender universo criado por Guillermo del Toro.', 2013, 'https://i.ytimg.com/vi/dFrm3hZGdRQ/maxresdefault.jpg', 'Criaturas monstruosas conhecidas como Kaiju começam a emergir do mar. Para combatê-los, a humanidade desenvolve uma série de robôs gigantescos, os Jaegers. Cada um é controlado por duas pessoas por meio de uma conexão neural. Entretanto, mesmo os Jaegers se mostram insuficientes para derrotar os Kaiju. Diante deste cenário, a última esperança é um velho robô, que passa a ser comandado por um antigo piloto e uma pessoa em treinamento.', 1);

INSERT INTO tb_role (authority) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_MEMBER');

INSERT INTO tb_user (name, email, password) VALUES ('Bob', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Ana', 'ana@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Alex', 'alex@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 2);

INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Filme muito top!', 3, 2);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Muito top mesmo, super engraçado!', 2, 2);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Sim verdade, bem divertido haha', 3, 2);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Que filme louco mano, legal de mais!', 2, 1);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Esse é de quebrar a cabeça kkk', 2, 1);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Não entendi muito bem.. mas é top os efeitos especiais', 3, 1);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Caraca!.. filme tem ação do começo a o fim!', 3, 3);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Optimus Prime é o cara mesmo em, ou melhor e a máquina mesmo em kkk', 2, 3);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Sim,.. Mas eu curti mais o Bumblebee kkk', 3, 3);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Mano... que filme louco cara.. cada vez que o portão do labirinto abria, meu coração parava O.o', 2, 4);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Pois e, coragem que eles têm para correrem naquele labirinto!', 3, 4);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Ótimo filme, parabéns a os produtores!', 3, 5);

